### PR TITLE
[packaging] Update to v3.0. Fixes JB#35860

### PR DESCRIPTION
**Pull request by izh1979**
Remove systemtap/ tree because we don't have any changes to upstream.
Rename upstream/ to systemtap/. Modify .gitmodules accordingly.
Bump version to 3.0.
Add systemd to both Requires and BuildRequires.

Signed-off-by: Igor Zhbanov igor.zhbanov@jolla.com

### CODE REVIEW

**Comment by saukko** [comment]
Maybe split the systemtap removal to separate commit for making review simpler? :)

**Comment by izh1979** [comment]
The directory systemtap/ was exactly the same as upstream/. The diff was only in .gitdir file.
So I simply removed old tree, and renamed empty upstream/ to systemtap/.

**Comment by izh1979** [comment]
All significant changes are in .gitmodules and rpm/systemtap.spec.

**Comment by izh1979** [comment]
Split to two commits.

**Comment by izh1979** [comment]
Builds successfully in feature branch project.

**Comment by izh1979** [comment]
Build successful. If any macros are to be removed, please show it to me. ;-)
Now I've tried to minimize the difference between upstream spec and ours.

**Comment by izh1979** [comment]
Updated the spec.

**Comment by saukko** [comment]
:+1:

**Pull request merged**
